### ISSUE TITLE
Imagen de fondo en home

### ISSUE THREAD

**Issue by taingus** [rodcorvalan/cuidobien#1]
La imagen es muy chica en algunas pantallas y no se redimensiona a los dispositivos, dejando la pantalla en un PC así (Tal vez no se nota pero tiene una franja blanca al costado):

![imagen](https://cloud.githubusercontent.com/assets/1969409/22927295/34d6bf3e-f28f-11e6-97a6-bb33337e73a4.png)

Y en un dispositivo móvil así (La imagen de fondo pasó a tener sólo la primer parte de la imagen original):

![imagen](https://cloud.githubusercontent.com/assets/1969409/22927321/580f06a0-f28f-11e6-92e7-5ba5e58b80bf.png)

**Comment by rodcorvalan** [comment]
Esta seccion todavia no la comienzo, use una imagen generica para probar el header en blanco
