### ISSUE TITLE
Alineación botones búsqueda

### ISSUE THREAD

**Issue by taingus** [rodcorvalan/cuidobien#2]
En algunos dispositivos (Se puede hacer redimensionando el navegador también), los botones de selección de opciones quedan mal alineados, deberían verse ó bien en una fila, o en una columna

![imagen](https://cloud.githubusercontent.com/assets/1969409/22927417/e464ce82-f28f-11e6-8fec-3c87878f7757.png)

**Comment by rodcorvalan** [comment]
Modificado, subido en el proximo commit
